application: dummy intro to parallel computing
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: series2.html
  upload: series2\.html

- url: /slide_config\.js
  static_files: slide_config.js
  upload: slide_config\.js

- url: /js
  static_dir: js

- url: /theme
  static_dir: theme

- url: /images
  static_dir: images
